name: cron job

on:
  schedule: 
    - cron: "* * * * *"
    - cron: "*/2 * * * *"

jobs:
  list-folder:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: list directories in root project
        run: |
          echo "directories in root"
          find . -maxdepth 1 -type d ! -name ".git" ! -name "." -printf "%f\n"
      - name: list the files in process management
        run: |
          echo "list the files in process management"
          ls -al "07-Process-Management"
      - name: list the contents in files
        run : |
          echo "list contents in files"
          cd 07-Process-Management
          cat README.md